language: python

python:
  - "2.7"
  - "3.5"

install:
  # pyta dependencies
  - pip install 'joblib>=0.11' 'numpy>=1.14.0' 'scipy>=1.0.0' 'nibabel>=2.3.2' 'matplotlib>=2.1.2' 'numba>=0.40.1' 'prox_tv'
  - pip install -e .

  # testing dependencies
  - pip install pytest coverage flake8 'pytest-cov<2.6.0' coveralls

script:
  # run unittests
  - set -e
  - flake8 --count pyta
  - pytest -vl --cov=pyta --cov-append
  # run examples
  - cd examples
  - python prox_s_example.py
  - python prox_t_example.py
  - python ta_example.py

after_success:
- bash <(curl -s https://codecov.io/bash)

notifications:
    email: false
