language: python

python:
  - "3.6"

install:
  # pyta dependencies
  - pip install 'joblib>=0.11' 'numpy>=1.14.0' 'scipy>=1.0.0' 'scikit-learn>=0.19.2' 'matplotlib>=2.1.2' 'prox_tv'
  - pip install  git+https://github.com/hcherkaoui/carpet.git
  - pip install -e .

  # testing dependencies
  - pip install pytest coverage flake8 'pytest-cov<2.6.0' coveralls

script:
  # run unittests
  - set -e
  - flake8 --count pyta
  - pytest -vl --cov=pyta --cov-append
  # run examples
  - cd examples
  - python simple_example.py --seed 0 --solver-type iterative-z-step --max-iter 1

after_success:
- bash <(curl -s https://codecov.io/bash)

notifications:
    email: false
